version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    labels: ["type: chore"]

  - package-ecosystem: swift
    directory: /Packages/TaktKit
    schedule:
      interval: weekly
    commit-message:
      prefix: build
      include: scope
    labels: ["type: chore"]

  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: monthly
    commit-message:
      prefix: build
      include: scope
    labels: ["type: chore"]
    groups:
      site:
        patterns: ["*"]
