name: PR-Titel

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  conventional-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            perf
            refactor
            test
            docs
            build
            ci
            chore
          scopes: |
            core
            store
            ui
            system
            ado
            analytics
            calendar
            app
            release
            deps
            site
            main
          requireScope: false
